# https://taskfile.dev
version: '3'
includes:
  all:
    taskfile: Taskfile.all.yml
tasks:
  version:
    desc: Показать текущую версию
    cmd: |
      git describe --tags --abbrev=0 2>/dev/null
    silent: true
